### ISSUE TITLE
Update to reference ILRepack 1.23

### ISSUE THREAD

**Issue by rcollette** [peters/ILRepack.MSBuild.Task#10]
A bug related to anonymous types was fixed in ILRepack.

**Comment by XVincentX** [comment]
:+1: 
Please update the reference, we're over a year behind the actual version!

**Comment by StanleyGoldman** [comment]
+1

**Comment by laedit** [comment]
:+1:

**Comment by rcollette** [comment]
Closing because there is a newer version and someone else already posted an issue to update to the latest version.
