### ISSUE TITLE
Please update to ILRepack 1.25

### ISSUE THREAD

**Issue by deniszykov** [peters/ILRepack.MSBuild.Task#12]
https://github.com/gluck/il-repack/issues/58 and other issues

**Comment by lploumen** [comment]
Yes, it would be great if you could upgrade the latest ILRepack version !

**Comment by OmerRaviv** [comment]
+1

**Comment by peters** [comment]
I stopped maintaining this project a year ago, but if you submit a PR i'll gladly merge it :)

**Comment by lploumen** [comment]
I would gladly submit a pull request if I was able to build the project.
Do you have any documentation about how to build the project (needed dependencies and so on... ) ?

**Comment by peters** [comment]
Simple:

- 1. git clone this project
- 2. git submodule update --init --update
- 3. cd deps/ilrepack -> update to latest version
- 4. open solution
- 5. restore nuget packages (the old way, :zzz:)
- 6. build (see: https://github.com/peters/ILRepack.MSBuild.Task/blob/master/src/msbuild/ILRepack.MSBuild.Task.csproj#L57)

**Comment by lploumen** [comment]
As I don't see any benefits anymore to use the task, I use a post build event.
