### ISSUE TITLE
Automatically pack all assemblies when referencing nuget package

### ISSUE THREAD

**Issue by icnocop** [peters/ILRepack.MSBuild.Task#13]
Thank you for ILRepack.MSBuild.Task.

I would like to request that all referenced assemblies marked as "Copy Local" be packed automatically when referencing the nuget package.

For example, the following msbuild task should be injected:

```
  <!-- ILRepack -->
  <Target Name="AfterBuild">

     <ItemGroup>
      <InputAssemblies Include="$(OutputPath)\*.dll" />
     </ItemGroup>

     <ILRepack 
      Parallel="true"
      Internalize="false"
      InputAssemblies="@(InputAssemblies)"
      TargetKind="Dll"
      ZeroPeKind="true"
      OutputFile="$(OutputPath)\$(AssemblyName).dll" />

  </Target>
  <!-- /ILRepack -->
```

In this way it's _very_ easy to internalize all assemblies of the project.

The nuget package will need to detect if the project's output is a dll or exe and update the msbuild task accordingly.

Thank you.

**Comment by peters** [comment]
@icnocop This is now support. Please checkout the readme on how to use wildcards.
