### ISSUE TITLE
repack not working when wildcard used for InputAssemblies="*.dll" 

### ISSUE THREAD

**Issue by karlisf** [peters/ILRepack.MSBuild.Task#29]
The section ["ILRepack a library and all dependencies"](https://github.com/peters/ILRepack.MSBuild.Task#ilrepack-a-library-and-all-dependencies) of documentation says that wildcard could be used:
`InputAssemblies="*.dll".`

When it's used no additional dll's are included because the part "LibraryToRepack.dll *.dll" of output is erroneous:
`ILRepack: Input assemblies (using input assembly wildcards): C:\Users\**\Documents\Visual Studio 2017\Projects\RepackSample\LibraryToRepack\bin\Debug\LibraryToRepack.dll *.dll.`

When value of InputAssembly is changed to:
`InputAssemblies="$(OutputPath)\*.dll"`
everything works. 

I guess it's error in the documentation.

**Comment by peters** [comment]
Thanks for that. I've updated the documentation accordingly.
